env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
dist: ../../dist
builds:
  - goos:
      - darwin
      - linux
      - windows
    ldflags:
      - -s -w -X main.name={{.Env.MAIN}} -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
      - -X main.buildDate={{.Env.BUILD_DATE}}
