env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
dist: bin/dist
builds:
{{range (file.ReadDir "cmd")}}
  - id: "{{.}}"
    binary: "{{.}}"
    main: "./cmd/{{.}}"
    goos:
      - darwin
      - linux
      - windows
    ldflags:
      - -s -w -X main.name={{.}} {{env.Getenv "LDFLAGS"}}
{{end}}
