default: "help"
expose: ["help", "info", "promote", "refresh", "compile", "release", "publish"]
configuration: ~/.dockerhub.yml
# ~/.dockerhub.yml should contains:
# DOCKERHUB_USER: <your dockerhub user>
# DOCKERHUB_PASS: <your dockerhub password or a dockerhub token>

properties:
  # Build Configuration (edit this section to override default values)
  MODULE: "" # leave empty to default to the git remote url (e.g. "github.com/<usename>/<reponame>")
  PROJECT: "" # leave empty to default to the git repository name (e.g. "<reponame>")
  LDFLAGS: "" # add custom standard ldflags, will be applied everywhere everytime
  BUILD_DIR: "bin" # subfolder where the build will output
  # Build parameters (use the -props flag to change these default values)
  latest: false # Do not tag the Docker image with latest, specify othewise with `-props "{latest: true}"`
  ldflags: "" # Specify a additional ldflags with `-props "{ldflags: '<flags>'}"`
  buildpaths: [] # By default, all paths under the cmd/ folder are built, specify a different folder list with `-props "{buildpaths: ["other/path", "to/build"]}"`
  linters: [] # List of linters to run on the lint target, if left empty : run all fast linters
  lintersno: ["scopelint", "forbidigo"] # List of linters to exclude on running the lint target

targets:
  help:
    doc: "print this message"
    steps:
      # - $: 'neon -info' => incorrect order, issue to open
      - color: "cyan"
        print: "Available targets"
      - print: ""
      - print: "help     print this message"
      - print: "info     print build informations"
      - print: "promote  promote the project with a new tag based on git log history"
      - print: "refresh  refresh go modules (add missing and remove unused modules) [will trigger: info]"
      - print: "compile  compile binary files locally [will trigger: info->refresh]"
      - print: "test     run all tests with coverage [will trigger: info->refresh->compile]"
      - print: "lint     examine source code and report suspicious constructs [will trigger: info->refresh->compile->test]"
      - print: "release  compile binary files for production [will trigger: info->refresh->compile->test->lint]"
      - print: "publish  publish binary files to Github and images to Dockerhub [will trigger: info->refresh->compile->test->lint->release]"
      - print: ""
      - print: 'Example : neon -props "{latest: true}" promote publish'

  info:
    doc: "print build informations"
    steps:
      - $: "git describe --tags --exact-match 2>/dev/null || git symbolic-ref -q --short HEAD"
        1=: "tag"
        3x: true
      - $: 'echo -n "={tag}" | sed -e s/^v//'
        1=: "version"
        3x: true
      - $: "git rev-parse HEAD 2>/dev/null"
        1=: "commit"
        3x: true
      - "date = now()[0:10]"
      - try:
          - $: "git config user.email"
            1=: "by"
            3x: true
        catch:
          - print: "User email not defined, use 'git config user.email <your email>'"
          - $: "exit 1"
      - $: 'if expr match "={version}" "\d\+\.\d\+\.\d\+" 1>/dev/null 2>&1; then echo -n "yes"; else echo -n "no"; fi'
        1=: "is_release"
        3x: true
      - $: "cut -f1 -d."
        <: "=version"
        1=: "version_major"
        3x: true
      - $: "cut -f2 -d."
        <: "=version"
        1=: "version_minor"
        3x: true
      - $: "cut -f3 -d."
        <: "=version"
        1=: "version_patch"
        3x: true
      - if: MODULE == ""
        then:
          - $: "git config --local remote.origin.url|sed -n 's#^.*//\\(.*\\)\\.git$#\\1#p'" # .*//(.*)\.git => https://github.com/<user>/<repo>.git => github.com/<user>/<repo>
            1=: "mod"
            3x: true
        else:
          - $: "echo -n ={MODULE}"
            1=: "mod"
            3x: true
      - if: PROJECT == ""
        then:
          - $: "cut -f3 -d/"
            <: "=mod"
            1=: "project"
            3x: true
        else:
          - $: "echo -n ={PROJECT}"
            1=: "project"
            3x: true
      - print: |-
          MODULE  = ={mod}
          PROJECT = ={project}
          TAG     = ={tag}
          COMMIT  = ={commit}
          DATE    = ={date}
          BY      = ={by}
          RELEASE = ={is_release}
      - if: 'is_release == "yes"'
        then:
          - print: |-
              VERSION = ={version_major}.={version_minor}.={version_patch}

  promote:
    doc: "promote the project with a new tag based on git log history"
    steps:
      - $: "git tag $(svu next || echo -n v0.1.0)"
        2x: true
      - $: "echo Promoted to $(svu current)"

  refresh:
    doc: "refresh go modules (add missing and remove unused modules)"
    depends: "info"
    steps:
      - $: "rm -f go.mod go.sum"
      - $: "go mod init ={mod}"
      - $: "go mod tidy"

  compile:
    doc: "compile binary files locally"
    depends: ["info", "refresh"]
    steps:
      - ldflags = ldflags + " -X main.version=" + tag + " -X main.commit=" + commit + " -X main.buildDate=" + date + " -X main.builtBy=" + by
      - if: len(buildpaths) == 0
        then:
          - buildpaths = appendpath("cmd", find("cmd", "*"))
      - for: path
        in: buildpaths
        do:
          - print: Building ={path}
          - |
            pathcomponents = split(unixpath(path), "/")
            name = pathcomponents[len(pathcomponents)-1]
          - $: go build -ldflags "-X main.name=={name} ={ldflags} ={LDFLAGS}" -o ./={BUILD_DIR}/={name} ./={path}

  test:
    doc: "run all tests with coverage"
    depends: ["info", "refresh", "compile"]
    steps:
      - $: go test -coverprofile=./={BUILD_DIR}/coverage.txt -covermode=atomic ./...

  lint:
    doc: "examine source code and report suspicious constructs"
    depends: ["info", "refresh", "compile", "test"]
    steps:
      - if: len(linters) == 0
        then:
          - $: golangci-lint run --fast --enable-all ={replace(join(appendpath("--disable", lintersno), " "), "/", " ")}
            :: true
        else:
          - $: golangci-lint run ={replace(join(appendpath("--enable", linters), " "), "/", " ")} ={replace(join(appendpath("--disable", lintersno), " "), "/", " ")}
            :: true

  build-docker:
    doc: "build docker images locally"
    unless: 'newer("={BUILD_DIR}/last", find(".", "Dockerfile", "**/*.sh", ".zshrc", ".p10k.zsh"))'
    depends: ["info", "refresh"]
    steps:
      - print: "Executing build target"
        color: cyan
      - mkdir: =BUILD_DIR
      - $: "echo TODO"
    #- $: 'sudo docker build -q --iidfile build/last -t adrienaury/go-devcontainer:={tag} --target go-devcontainer .'

  # run "neon -props '{latest: true}' release" to include latest tag
  release:
    doc: "build docker images locally with tagged versions"
    # unless: 'is_release != "yes"' => is_release unknown variable, issue to open
    depends: ["info", "refresh", "build"]
    steps:
      - if: 'is_release == "yes"'
        then:
          - $: "echo TODO"
          # - $: 'sudo docker tag adrienaury/go-devcontainer:={tag} adrienaury/go-devcontainer:v={version_major}'
          # - $: 'sudo docker tag adrienaury/go-devcontainer:={tag} adrienaury/go-devcontainer:v={version_major}.={version_minor}'
          - if: "latest"
            then:
              - $: "echo TODO"
            # - $: 'sudo docker tag adrienaury/go-devcontainer:={tag} adrienaury/go-devcontainer:latest'
          - $: "sudo docker images --no-trunc | grep $(cat ={BUILD_DIR}/last)"
        else:
          - print: "Skipping release target (not a release)"
            color: red

  docker-login:
    steps:
      - try:
          - $: "sudo docker login -u ={DOCKERHUB_USER} -p ={DOCKERHUB_PASS}"
            2x: true
        catch:
          - print: |
              To use this target, make sure your credentials are valid in the file ~/.dockerhub.yml
              The content of the file should be :
                DOCKERHUB_USER: <your dockerhub user>
                DOCKERHUB_PASS: <your dockerhub password or a dockerhub token>
          - $: return 1

  # run "neon -props '{latest: true}' publish" to include latest tag
  publish:
    doc: "push docker images to Dockerhub"
    # unless: 'is_release != "yes"' => is_release unknown variable, issue to open
    depends: ["info", "release", "docker-login"]
    steps:
      - if: 'is_release == "yes"'
        then:
          - $: "echo TODO"
          # - $: 'sudo docker push adrienaury/go-devcontainer:={tag}'
          # - $: 'sudo docker push adrienaury/go-devcontainer:v={version_major}'
          # - $: 'sudo docker push adrienaury/go-devcontainer:v={version_major}.={version_minor}'
          - if: "latest"
            then:
              - $: "echo TODO"
            # - $: 'sudo docker push adrienaury/go-devcontainer:latest'
        else:
          - print: "Skipping release target (not a release)"
            color: red
